Add additional hash parameters for the remaining defined types
voxpupuli/puppet-systemd pull request #212
Opened 2021-08-12 20:26 UTC by silug

#### Pull Request (PR) description
This adds parameters to manage the following resources via Hiera:
* `systemd::network`
* `systemd::timer`
* `systemd::tmpfile`
* `systemd::unit_file`

#### This Pull Request (PR) fixes the following issues
N/A

2021-08-12 20:43 UTC, ghoneycutt requested changes

2021-08-12 20:43 UTC, ghoneycutt commented on data/common.yaml
> +lookup_options:
This is not a standard pattern and would caution against specifying the lookup strategy. Usually this is not needed and if it is, that is managed outside a module.

2021-08-12 20:43 UTC, ghoneycutt commented on manifests/init.pp
> +  Hash[String,Hash[String, Any]]                         $loginctl_users,
Could you please add spec tests for these? Here's an example at https://github.com/ghoneycutt/puppet-module-bind/blob/master/spec/classes/init_spec.rb#L511-L534 

You specify params with a valid hash and then check to see that the defined types are in the catalog.

2021-08-12 20:43 UTC, ghoneycutt commented
Thanks for this contribution!

2021-09-07 10:15 UTC, bastelfreak commented
Hi,
thanks for the PR. I'm going to close this since we merged the changes in https://github.com/voxpupuli/puppet-systemd/pull/223.

2021-09-07 10:15 UTC, closed without merging