Support Debian 12
voxpupuli/puppet-systemd pull request #357
Opened 2023-06-27 08:06 UTC by traylenator

#### Pull Request (PR) description

In particular with Debian 11->12 systemd-resolved is now a sub package
that must be installed.

2023-06-27 08:09 UTC, traylenator commented
Needs a bit more testing as enabling with:

```puppet
class{'systemd':
  manage_resolved   => true,
  use_stub_resolver => true,
}
```
I lost DNS. ( fixed by reboot and now running and  using systemd-resolved )

2023-06-27 20:34 UTC, traylenator commented
> Needs a bit more testing as enabling with:
> 
> ```puppet
> class{'systemd':
>   manage_resolved   => true,
>   use_stub_resolver => true,
> }
> ```
> 
> I lost DNS. ( fixed by reboot and now running and using systemd-resolved )

Understood - not relevent.

2023-08-07 08:36 UTC, rh-org commented
LGTM

2023-08-07 08:39 UTC, saz commented
LGTM.

We should think about, installing `systemd-resolved` and `systemd-timesyncd` by default and just disable it on Debian 10(?) and 11, if required. Currently, any newer Debian release might "break", as the packages are missing, no configuration is happening, but at the same time, there won't be any error message.

2023-10-12 16:42 UTC, anarcat approved these changes
LGTM.

2023-10-13 06:11 UTC, tuxmea approved these changes

2023-10-13 08:21 UTC, traylenator commented
@tuxmea Did you try migrating with this - I do loose initially which I never really understood?

2023-10-13 09:46 UTC, ekohl commented
FYI: https://github.com/voxpupuli/puppet_metadata/pull/102 would add Debian 12 to acceptance tests using distro packages so you at least have Puppet 7 to test with.

2023-10-18 19:21 UTC, ekohl requested changes
If we apply this with https://github.com/voxpupuli/modulesync_config/pull/855 we should have at least some acceptance test.

2023-10-29 20:16 UTC, ekohl commented
I took the liberty of rebasing this.

2023-10-29 20:18 UTC, ekohl commented on spec/acceptance/resolved_spec.rb
> +      end
For systemd-networkd I extracted this to a separate variable:
https://github.com/voxpupuli/puppet-systemd/blob/5f64bc177c6c1a39b557292840a46c7954dc9f05/spec/acceptance/networkd_spec.rb#L6

Then I reused it to check if the package is installed:
https://github.com/voxpupuli/puppet-systemd/blob/5f64bc177c6c1a39b557292840a46c7954dc9f05/spec/acceptance/networkd_spec.rb#L32

2023-10-29 22:26 UTC, ekohl approved these changes

2023-10-29 22:30 UTC, bastelfreak approved these changes

2023-10-29 22:32 UTC, merged