Add loginctl_linger_users fact
voxpupuli/puppet-systemd pull request #410
Opened 2024-02-05 20:06 UTC by jcpunk

#### Pull Request (PR) description
Add a fact listing users with linger enabled.

As near as I can tell from the systemd source, `root` is always able to linger even it not setup explicitly.

#### This Pull Request (PR) fixes the following issues

2024-02-05 20:23 UTC, zilchms requested changes

2024-02-05 20:23 UTC, zilchms commented on spec/unit/facter/loginctl_linger_users_spec.rb
> +        expect(Facter.value(:loginctl_linger_users)).to eq(['abc', 'test', 'root'])
try %w[abc test root] instead of ['abc', 'test', 'root']

2024-02-05 21:32 UTC, zilchms approved these changes
I am willing to let it pass with the tests written the way they are, but i would suggest we find someone with better rspec knowledge to go over it too before we merge

2024-02-05 23:02 UTC, h0tw1r3 commented
Generally not in favor of adding facts like this, particularly on widely used modules. A function or resource may be more appropriate.

That said, what's an sample use case?

2024-02-05 23:02 UTC, h0tw1r3 requested changes
Generally not in favor of adding facts like this, particularly on widely used modules. A function or resource may be more appropriate.

That said, what's an sample use case?

2024-02-06 03:32 UTC, jcpunk commented
My overall plan is to feed this value back into
```
systemd::logind_settings:
    KillExcludeUsers:
```
So my users with `linger` will have the ability to trivially persist processes.

Pat

2024-02-06 05:17 UTC, h0tw1r3 commented
I'm confused, isn't that redundant if touching a /var/lib/systemd/linger/<user> file is the same as adding <user> to KillExcludeUsers in the logind conf file?

2024-02-06 09:52 UTC, traylenator commented
> I'm confused, isn't that redundant if touching a /var/lib/systemd/linger/ file is the same as adding to KillExcludeUsers in the logind conf file?

Maybe a slight difference:

I guess enable linger will stop things being killed that are running in the `systemd --user` scope however all other user processes would be killed. Better to encourage users to run long lived processes  in the correct context if they want them to survive.

I'm kind of worried about this fact as it would be pretty large in our case.

2024-02-06 14:38 UTC, jcpunk commented
If this fact looks to be too much, I can always run it out of one of my private modules.  Just figured I'd default to "share with the community".

2024-02-06 15:05 UTC, h0tw1r3 commented
> I'm kind of worried about this fact as it would be pretty large in our case.

Agree. My basic objection to a fact like this.

2024-02-06 15:30 UTC, jcpunk commented
No worries, I'll close this out and run the fact privately.

2024-02-06 15:30 UTC, closed without merging

2024-02-07 10:18 UTC, traylenator commented
If I was going to do this and am actually thinking about it I would not rely on puppet to maintain that list. I'd set up a path unit and service and sync `/var/lib/systemd/linger` entries to `KillExcludeUsers` settings.