#1346 - Update deprecated shell_escape function
voxpupuli/puppet-systemd pull request #480
Opened 2024-07-18 17:06 UTC by jormaster3k

For stdlib 9.x and later, the shell_escape function has been moved to stdlib::shell_escape.

This change breaks compatiblity with stdlib 8.x

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

Fixes #479

2024-07-20 07:05 UTC, kenyon requested changes
Can you also update the minimum stdlib version in `metadata.json`? Thanks.

2024-07-22 19:27 UTC, kenyon approved these changes

2024-07-23 17:06 UTC, smortex approved these changes

2024-07-29 11:57 UTC, TheMeier approved these changes

2024-07-29 12:18 UTC, merged